sudo: true
dist: xenial

language: python
cache: pip
matrix:
  include:
    - python: 3.7
      env: BLACK_CHECK=true
    - python: 3.6
    - python: 3.5
    - python: 2.7

before_install:
  - pip install -U pip setuptools wheel

install:
  - pip install -r requirements.txt -r test_requirements.txt

script:
  - pytest
  - '[ "$SKIP_BLACK" != "true" ] || black --check .'
  - isort --check-only --diff --recursive
  - pylint pylint_sqlalchemy tests
  - npx eclint check $(git ls-files)
